"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import sys

try:
    import silk  # noqa: F401
    SILK_INSTALLED = True
except ImportError:
    SILK_INSTALLED = False

try:
    import drf_spectacular  # noqa: F401
    SPECTACULAR_INSTALLED = True
except ImportError:
    SPECTACULAR_INSTALLED = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7q(@xng)ddrb^f)7x8u#-=^e^1nb5zu2qv)9g=w!ve5-cyeey&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# True when running `manage.py test` — disables Redis/Celery for hermetic runs.
TESTING = 'test' in sys.argv or os.environ.get('PETSHOP_TESTING') == '1'


# Application definition

INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
]

if SILK_INSTALLED:
    INSTALLED_APPS.insert(0, 'silk')

if SPECTACULAR_INSTALLED:
    INSTALLED_APPS.append('drf_spectacular')

MIDDLEWARE = [
    'core.api.middleware.RequestIdMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if SILK_INSTALLED:
    MIDDLEWARE.insert(1, 'silk.middleware.SilkyMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Redis + caching
# ---------------------------------------------------------------------
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'petshop',
        'TIMEOUT': 300,
    }
}

# Celery (async tasks + beat) — Redis as broker/result backend
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/1')
CELERY_TIMEZONE = 'UTC'  # matches TIME_ZONE below
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = True

# How long versioned entity caches stay alive (seconds)
CACHE_TTL_CATALOG = int(os.environ.get('CACHE_TTL_CATALOG', '600'))
CACHE_TTL_PRODUCTS = int(os.environ.get('CACHE_TTL_PRODUCTS', '120'))

if TESTING:
    # Hermetic test runs: no Redis server needed, tasks run synchronously.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'KEY_PREFIX': 'petshop-test',
        }
    }
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Local demo: serve static assets (DRF browsable API, admin) via the finders
# even with DEBUG=False. Set SERVE_STATIC_FILES=0 behind nginx/collectstatic.
SERVE_STATIC_FILES = os.environ.get('SERVE_STATIC_FILES', '1') != '0'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# CORS - Telegram Mini App / SPA integratsiyasi uchun
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://webapp.petshop.uz",
]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Response standard: envelope renderer + global exception handler
    'DEFAULT_RENDERER_CLASSES': [
        'core.api.responses.AppJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'EXCEPTION_HANDLER': 'core.api.exception_handler.app_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'core.api.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Response standard: mock/demo endpoints for frontend development
ENABLE_MOCKS = True

# --- Telegram Mini App (TMA) password auth --------------------------------
# Bot created via @BotFather; used to (a) validate TMA initData hashes and
# (b) deliver the one-time login password straight to the user's chat.
# Without a token the hash is not verified and passwords are written to the
# server log only (demo mode) — set TELEGRAM_BOT_TOKEN before going live.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# How old an initData `auth_date` may be before it is rejected (seconds).
TELEGRAM_AUTH_MAX_AGE = int(os.environ.get('TELEGRAM_AUTH_MAX_AGE', '86400'))

# Monitoring: django-silk (demo: open access; restrict before production)
if SILK_INSTALLED:
    SILKY_AUTHENTICATION = False
    SILKY_AUTHORISATION = False
    SILKY_PYTHON_PROFILER = False
    SILKY_MAX_RESPONSE_BODY_SIZE = 1024 * 512
    # Don't record every static asset / silk's own UI (just DB bloat + noise)
    SILKY_IGNORE_PATHS = ['/static/', '/silk/']

# OpenAPI schema (drf-spectacular)
if SPECTACULAR_INSTALLED:
    SPECTACULAR_SETTINGS = {
        'TITLE': 'PetShop API',
        'DESCRIPTION': 'PetShop e-commerce & veterinary services API — standardized response envelope.',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'COMPONENT_SPLIT_REQUEST': True,
    }
